name: Deploy GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: npm install and deploy
      run: |
        npm ci
        npm run deploy
      env:
        CI: true
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
