name: Deploy GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'

    - name: npm install and deploy
      run: |
        npm ci
        npm run deploy
      env:
        CI: true
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
